stages:
  dataIngestion:
    cmd: python src/dataIngestion.py
    deps:
    - src/dataIngestion.py
    params:
    - dataIngestion.test_size
    outs:
    - data/initial
  dataPreprocessing:
    cmd: python src/dataPreprocessing.py
    deps:
    - data/initial
    - src/dataPreprocessing.py
    outs:
    - data/interim
  featureEngineering:
    cmd: python src/featureEngineering.py
    deps:
    - data/interim
    - src/featureEngineering.py
    params:
    - featureEngineering.max_features
    outs:
    - data/processed
  modelBuilding:
    cmd: python src/modelBuilding.py
    deps:
    - data/processed
    - src/modelBuilding.py
    params:
    - modelBuilding.n_estimators
    - modelBuilding.random_state
    outs:
    - models/model.pkl
  modelEval:
    cmd: python src/modelEval.py
    deps:
    - models/model.pkl
    outs:
    - reports/metrics.json
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
